layoutdir = "themes/hugo-academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://liuxslab.netlify.com/"
canonifyurls = true
theme = "hugo-academic-group"
title = "Xue-Song Liu lab"
math = true
copyright = "&copy; LiuXS Lab 2018 -- all rights reserved"
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Xue-Song Liu"
  email = "liuxs@shanghaitech.edu.cn"
  phone = "20684520"
  address = "L building A406, ShanghaiTech. University, 393 Middle Huaxia Road, Pudong District, Shanghai"

  slogan = "Laboratory of Cancer Biology"
  slogan_text = "LiuXS Lab, ShanghaiTech University"

  [params.logo]
    image = "img/logo_red.svg"
    link = "http://www.shanghaitech.edu.cn/main.htm"

#  [[params.navbar_hierarchy]]
#    name = "LiuXS Lab"
#    link = "https://liuxslab.netlify.com/"
#    position = 1

  [[params.slogan_columns]]
    title = ""
    text = ""
 #   link = "/approach"
 #   link_text = "Read more"
    weight = 1
 #   weight = 3
  
  [[params.slogan_columns]]
    title = ""
    text =  "Xue-Song Liu lab study the fundamental difference between cancer cell and normal somatic cell. With a purpose to identify cancer specific biomarkers and therapeutic targets. Multiple approaches, including cell biochemistry, bioinformatics and mouse modeling, are combined to investigate the basic mechanisms in cancer."
    link = "/research"
    link_text = "Read more"
    weight = 2
  
 # [[params.slogan_columns]]
 #   title = "Mission"
 #   text = "Per peterem ex, Eurystheus videt maeonis, Paeonis uritur. Dextera [legem](http://nubibus.net/qualisardeat), contigerat optabile undis bene: abis sperato. Instrumenta arma, subiectas generis non ipsa patres quia magna Messeneque lacrimaeque torva. Aequo crescunt inrequieta feras, diu illa est occupat aequoribus hunc Elpenora tollens vult robore. Finiat priora vulnere nec Nelei fit quae totidemque intibaque iter longo."
 #   link = "/mission"
 #   link_text = "Read more"
 #   weight = 2



  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 5
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  [params.vacancies]
    title = "Teaching"
    subtitle = ""
    count = 3
    str_all = "More Classes"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "#top"
      weight = 1


  [[menu.main]]
      name = "Publications"
      url = "#publications"
      weight = 2

  [[menu.main]]
      name = "Projects"
      url = "#projects"
      weight = 3

  [[menu.main]]
      name = "Members"
      url = "#members"
      weight = 4
  [[menu.main]]
      name = "Teaching"
      url = "#vacancies"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "#posts"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 7
      

